### ISSUE TITLE
Referential On Match Set Properties

### ISSUE THREAD

**Issue by NOT-HAL9000** [Accenture/Cymple#17]
How would I build something like this? 

How do I reference ```n.likes``` and build the expression within the ```on_match().set({"n.likes": _WHAT GOES HERE_ })``` dictionary. 

```MERGE (n:NODE, {name: 'test'}) ON CREATE SET n.likes = 0 ON MATCH SET n.likes = n.likes + 1```

**Comment by Yael-Zamir** [comment]
Hi @NOT-HAL9000 ,

Thank you for the report!
The issue has been fixed, merged and deployed. 

Fix details: The set function now receives a new boolean argument called escape_value which when set to False, the values will not be enclosed by quotation marks.

The query from your request can be built using the following code:

![image](https://user-images.githubusercontent.com/117284121/220338769-ad231b4d-b812-4a1a-8c1e-c54d4c1afa7e.png)
