### ISSUE TITLE
[Question] How to make a query for adding several nodes (edges, nodes + edges)?

### ISSUE THREAD

**Issue by Claus1** [Accenture/Cymple#34]
I didn't find a way in Cymple doc and sources for adding several nodes (edges, nodes + edges) in a query. Is it possible?
For example how to build
```
WITH [
  {name: 'Alice', age: 30},
  {name: 'Bob', age: 25},
  {name: 'Charlie', age: 35}
] AS people
UNWIND people AS person
CREATE (p:Person {name: person.name, age: person.age})
RETURN p
```

**Comment by Roei-Levi** [comment]
Hi, 

Try
`qb = QueryBuilder()

people_str = '''[
  {name: 'Alice', age: 30},
  {name: 'Bob', age: 25},
  {name: 'Charlie', age: 35}
]'''

query = (qb.with_(f'{people_str} AS people\n')
            .unwind('people AS person')
            .create()
            .node('Person', 'p', {'name': 'person.name', 'age': 'person.age'}, escape=False)
            .return_literal('p'))`

or, when using parameters,
`query = (qb.with_('$people AS people')
            .unwind('people AS person')
            .create()
            .node('Person', 'p', {'name': 'person.name', 'age': 'person.age'}, escape=False)
            .return_literal('p'))`

**Comment by Claus1** [comment]
Thanks!
> or, when using parameters,

It is not clear what you mean. 
Usually we have a list for adding like
```
nodes = [{'name': 'Alice', 'age': 30}, {'name': 'Bob', age: 25},   {'name': 'Charlie', 'age': 35}]
```
Computing 'people_str' using pure python is cumbersome. Can we form a query from 'nodes' list of dictionaries?

**Comment by Roei-Levi** [comment]
I just meant using parameters passed to the driver when executing the query, see [here](https://neo4j.com/docs/python-manual/current/query-simple/#query-parameters).

**Comment by Claus1** [comment]
Thanks! 
> I just meant using parameters passed to the driver when executing the query, see [here](https://neo4j.com/docs/python-manual/current/query-simple/#query-parameters).
Cypher is used not only in neo4j. My choice, for example, is kuzu.
