### ISSUE TITLE
No " RETURN CASE WHEN" after a MATCH 

### ISSUE THREAD

**Issue by TechInTerh** [Accenture/Cymple#37]
I'm using Cymple and it is great !
But, the statement  "RETURN CASE ... WHEN .... THEN ....." Is not implemented.
"case_when" exist only after a DELETE statement.

Example from [docs](https://neo4j.com/docs/cypher-manual/current/queries/case/)
```sql
MATCH (n:Person)
RETURN
CASE n.eyes
  WHEN 'blue'  THEN 1
  WHEN 'brown', 'hazel' THEN 2
  ELSE 3
END AS result, n.eyes
```
With Cymple syntax, it would be something like: 
```python
QueryBuilder().match().nodes(ref_name="n", labels = "Person")
    .return_case(expression="n.eyes").when("blue").then("1")
    .when(['brown','hazel']).then("2") # or " 'brown', 'hazel' "
    .else("3").end_as("result, n.eyes")
```

It would be great to have it !
I can develop the new relation if I have time.

**Comment by Yael-Zamir** [comment]
Hi @TechInTerh,

Thank you for the report!
The issue has been fixed, merged and deployed. 
 
Fix details: we've added a new function named 'case', that is different from the old 'case_when' ('case_when' remained for backward compatibility). The new function receives the following arguments: 
 

- test_expression: An optional argument. An expression to test the cases against.
- when_then_mapping: A dictionary such that: 
  - A value represents a literal expression (or a list of expressions) whose result will be compared to test_expression if given, else is evaluated to a BOOLEAN,
  - And it's key represents the literal expression returned as output if the value matches test_expression if giver, or if the expression evaluates to TRUE.
- default_result: The expression to return if no value matches the test expression if given, or if all expressions evaluated as FALSE.
- results_ref: The reference name of the resulted returned values, plus any other desired reference names to return.

 
Here are all the examples that appear in the [docs](https://neo4j.com/docs/cypher-manual/current/queries/case/), written using the new function (including the one provided by you):
 
**Simple Case**:

```python
(QueryBuilder().match().node(ref_name="n", labels="Person")
    .return_literal()
    .case(
    when_then_mapping={
        "1": "'blue'",
        "2": ["'brown'", "'hazel'"]
    },
    default_result="3",
    results_ref="result, n.eyes", test_expression="n.eyes"
))
```

result:

```cypher
MATCH (n:Person)
RETURN
CASE n.eyes
  WHEN 'blue'  THEN 1
  WHEN 'brown', 'hazel' THEN 2
  ELSE 3
END AS result, n.eyes
```
 
**Extended Simple Case:**

```python
(QueryBuilder().match().node(ref_name="n", labels="Person")
    .return_literal("n.name,")
    .case(
        when_then_mapping={
            "'Unknown'": ["IS NULL", "IS NOT TYPED INTEGER | FLOAT"],
            "'Baby'": ["= 0", "= 1", "= 2"],
            "'Child'": "<= 13",
            "'Teenager'": "< 20",
            "'Young Adult'": "< 30",
            "'Immortal'": "> 1000"},
        default_result="'Adult'",
        test_expression="n.age",
        results_ref="result"))
```
 
result:

```cypher
MATCH (n:Person)
RETURN n.name,
CASE n.age
  WHEN IS NULL, IS NOT TYPED INTEGER | FLOAT THEN "Unknown"
  WHEN = 0, = 1, = 2 THEN "Baby"
  WHEN <= 13 THEN "Child"
  WHEN < 20 THEN "Teenager"
  WHEN < 30 THEN "Young Adult"
  WHEN > 1000 THEN "Immortal"
  ELSE "Adult"
END AS result
```
 
**Generic Case:**

```python
(QueryBuilder().match().node(ref_name="n", labels="Person")
 .return_literal()
 .case(
    when_then_mapping={
        "1": "n.eyes = 'blue'",
        "2": "n.age < 40"
    },
    default_result="3",
    results_ref="result, n.eyes, n.age"))
```

result:

```cypher
MATCH (n:Person)
RETURN
CASE
  WHEN n.eyes = 'blue' THEN 1
  WHEN n.age < 40      THEN 2
  ELSE 3
END AS result, n.eyes, n.age
```
 
 
**Generic Case with null Values:**

```python
(QueryBuilder().match().node(ref_name="n", labels="Person")
 .return_literal("n.name,")
 .case(
    when_then_mapping={
        "-1": "n.age IS NULL"
    },
    default_result="n.age - 10",
    results_ref="age_10_years_ago"))
```
 
result:

```cypher
MATCH (n:Person)
RETURN n.name,
CASE
  WHEN n.age IS NULL THEN -1
  ELSE n.age - 10
END AS age_10_years_ago
```
 
**CASE with succeeded SET:**

```python
(QueryBuilder().match().node(ref_name="n", labels="Person")
 .with_("n,")
 .return_literal()
 .case(
    when_then_mapping={
        "1": "'blue'", 
        "2": "'brown'"
    },
    default_result="3",
    results_ref="colorCode",
    test_expression="n.eyes")
 .set({
    "n.colorCode": "colorCode"
    },
    escape_values=False
).return_literal("n.name, n.colorCode"))
```

result:

```cypher
MATCH (n:Person)
WITH n,
CASE n.eyes
  WHEN 'blue'  THEN 1
  WHEN 'brown' THEN 2
  ELSE 3
END AS colorCode
SET n.colorCode = colorCode
RETURN n.name, n.colorCode
```

**Comment by TechInTerh** [comment]
Great, thanks!
